/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JRootPane;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        getTxtLugarOrigen = new javax.swing.JTextField();
        getTxtLugarDestino = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        precioVuelos = new javax.swing.JLabel();
        Volar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Ida = new javax.swing.JRadioButton();
        vuelta = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        getTxtNombre = new javax.swing.JTextField();
        getTxtApellidos = new javax.swing.JTextField();
        Equipaje = new javax.swing.JRadioButton();
        Maletas = new javax.swing.JRadioButton();
        Mascotas = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        iva = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ALERTA AEROPUERTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 17, -1, -1));

        jLabel2.setText("Origen:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel3.setText("Destino:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        getTxtLugarOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTxtLugarOrigenActionPerformed(evt);
            }
        });
        getContentPane().add(getTxtLugarOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 160, -1));
        getContentPane().add(getTxtLugarDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 164, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jButton1.setText("Resetear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));
        getContentPane().add(precioVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 110, 20));

        Volar.setText("Volar");
        Volar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolarActionPerformed(evt);
            }
        });
        getContentPane().add(Volar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        jLabel8.setText("Precio de vuelos:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        Ida.setText("Vuelo de ida");
        Ida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdaActionPerformed(evt);
            }
        });
        getContentPane().add(Ida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        vuelta.setText("Vuelo de vuelta");
        getContentPane().add(vuelta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jButton3.setText("Facturar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jLabel11.setText("Nombre:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel12.setText("Apellido:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));
        getContentPane().add(getTxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, -1));
        getContentPane().add(getTxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 140, -1));

        Equipaje.setText("Equipaje");
        getContentPane().add(Equipaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        Maletas.setText("Maletas");
        getContentPane().add(Maletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        Mascotas.setText("Mascotas");
        getContentPane().add(Mascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel4.setText("IVA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        getContentPane().add(iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getTxtLugarOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTxtLugarOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getTxtLugarOrigenActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void IdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdaActionPerformed

    private void VolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Equipaje;
    private javax.swing.JRadioButton Ida;
    private javax.swing.JRadioButton Maletas;
    private javax.swing.JRadioButton Mascotas;
    private javax.swing.JButton Volar;
    private javax.swing.JTextField getTxtApellidos;
    private javax.swing.JTextField getTxtLugarDestino;
    private javax.swing.JTextField getTxtLugarOrigen;
    private javax.swing.JTextField getTxtNombre;
    private javax.swing.JLabel iva;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel precioVuelos;
    private javax.swing.JRadioButton vuelta;
    // End of variables declaration//GEN-END:variables

    public JRadioButton getEquipaje() {
        return Equipaje;
    }

    public void setEquipaje(JRadioButton Equipaje) {
        this.Equipaje = Equipaje;
    }

    public JRadioButton getIda() {
        return Ida;
    }

    public void setIda(JRadioButton Ida) {
        this.Ida = Ida;
    }

    public JRadioButton getMaletas() {
        return Maletas;
    }

    public void setMaletas(JRadioButton Maletas) {
        this.Maletas = Maletas;
    }

    public JRadioButton getMascotas() {
        return Mascotas;
    }

    public void setMascotas(JRadioButton Mascotas) {
        this.Mascotas = Mascotas;
    }

    public JButton getVolar() {
        return Volar;
    }

    public void setVolar(JButton Volar) {
        this.Volar = Volar;
    }

    public JTextField getGetTxtApellidos() {
        return getTxtApellidos;
    }

    public void setGetTxtApellidos(JTextField getTxtApellidos) {
        this.getTxtApellidos = getTxtApellidos;
    }

    public JTextField getGetTxtLugarDestino() {
        return getTxtLugarDestino;
    }

    public void setGetTxtLugarDestino(JTextField getTxtLugarDestino) {
        this.getTxtLugarDestino = getTxtLugarDestino;
    }

    public JTextField getGetTxtLugarOrigen() {
        return getTxtLugarOrigen;
    }

    public void setGetTxtLugarOrigen(JTextField getTxtLugarOrigen) {
        this.getTxtLugarOrigen = getTxtLugarOrigen;
    }

    public JTextField getGetTxtNombre() {
        return getTxtNombre;
    }

    public void setGetTxtNombre(JTextField getTxtNombre) {
        this.getTxtNombre = getTxtNombre;
    }

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton3() {
        return jButton3;
    }

    public void setjButton3(JButton jButton3) {
        this.jButton3 = jButton3;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getiva() {
        return iva;
    }

    public void setiva(JLabel jLabel10) {
        this.iva = jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public void setjLabel11(JLabel jLabel11) {
        this.jLabel11 = jLabel11;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel13() {
        return jLabel13;
    }

    public void setjLabel13(JLabel jLabel13) {
        this.jLabel13 = jLabel13;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getPrecioVuelos() {
        return precioVuelos;
    }

    public void setPrecioVuelos(JLabel precioVuelos) {
        this.precioVuelos = precioVuelos;
    }

    public JRadioButton getVuelta() {
        return vuelta;
    }

    public void setVuelta(JRadioButton vuelta) {
        this.vuelta = vuelta;
    }

    public JRootPane getRootPane() {
        return rootPane;
    }

    public void setRootPane(JRootPane rootPane) {
        this.rootPane = rootPane;
    }

    public boolean isRootPaneCheckingEnabled() {
        return rootPaneCheckingEnabled;
    }

    public void setRootPaneCheckingEnabled(boolean rootPaneCheckingEnabled) {
        this.rootPaneCheckingEnabled = rootPaneCheckingEnabled;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }
    
    public void mostrarPrecio(double precioTotal, double iva) {
    // Aquí va el código para mostrar el precio y el IVA
    System.out.println("Precio total: " + precioTotal);
    System.out.println("IVA: " + iva);
    
    // Si estás mostrando los valores en la interfaz gráfica, puedes usar un JLabel o JTextField
    precioVuelos.setText("Precio total: " + precioTotal);
    
}
       public void resetearFormulario() {
        getTxtNombre.setText("");  // Limpia el campo de nombre
        getTxtLugarOrigen.setText("");  // Limpia el campo de origen
        getTxtLugarDestino.setText("");  // Limpia el campo de destino
        precioVuelos.setText("");  // Limpia el label del precio

        // Si tienes otros componentes que también deben ser reseteados, puedes hacerlo aquí.
        
        
    }

}